---
Name: stockconfig
---
#Extensions
SilverCommerce\CatalogueAdmin\Model\CatalogueProduct:
  extensions:
    - SilverCommerce\Stock\Extensions\ProductExtension
SilverCommerce\OrdersAdmin\Model\LineItem:
  extensions:
    - SilverCommerce\Stock\Extensions\LineItemExtension
SilverCommerce\OrdersAdmin\Model\Invoice:
  extensions:
    - SilverCommerce\Stock\Extensions\InvoiceExtension
SilverCommerce\CatalogueAdmin\Admin\CatalogueAdmin:
  extensions:
    - SilverCommerce\Stock\Extensions\CatalogueAdminExtension
