---
Name: stockconfig
---
#Extensions
SilverCommerce\CatalogueAdmin\Model\CatalogueProduct:
  extensions:
    - SilverCommerce\Stock\Extensions\ProductExtension
SilverCommerce\Checkout\Control\Checkout:
  extensions:
    - SilverCommerce\Stock\Extensions\CheckoutExtension
